### ISSUE TITLE
Add other alert methods

### ISSUE THREAD

**Issue by sdenike** [jeffpaulKinsta/kinsta-ip-checker#1]
It would be nice to include additional alert messages such as Pushover or Slack webhooks.

**Comment by jeffpaulKinsta** [comment]
Feel free to submit a pull request :trollface:

**Comment by sdenike** [comment]
In case I get around to it this is the code I would use for the alerts ;) 

`# Send pushover alert
curl -k https://api.pushover.net/1/messages.json -F token=TOKEN -F user=USER -F title="Kinsta" -F message="IP ADDRESS CHANGE MESSAGE"

# Slack alert
json="{\"channel\": \"#CHANNEL\", \"username\":\"Kinsta\", \"pretext\":\"IP ADDRESS CHANGE\", \"icon_emoji\":\":sunny:\", \"attachments\":[{\"color\":\"good\" , \"text\": \"IP ADDRESS CHANGE MESSAGE\"}]}"
curl -s -d "payload=$json" "https://hooks.slack.com/services/XXXXXX"`
